# Generated by Django 4.2.1 on 2023-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_app", "0004_book_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("surname", models.CharField(max_length=70)),
                ("feedback", models.CharField(max_length=70)),
            ],
        ),
    ]
